
[senura.repo_creation]
gitPAT = "<PAT>"
gitORG = "devant-test-org"
NAME ="sample-repo-name"

# Configuration file for "repo_creation"
# 
# This file contains configuration values for configurable variables in your Ballerina code.
# Both package-specific and imported module configurations are included below.
# 
# Learn more about configurable variables:
# https://ballerina.io/learn/provide-values-to-configurable-variables/#provide-via-toml-syntax
#
# Note: This file is automatically added to .gitignore to protect sensitive information.
